### ISSUE TITLE
Evaluate script

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_utils#66]
## Detailed Description
Make evaluation functions that takes in model results and looks at various metrics

input: pandas / csv - https://app.neptune.ai/o/OpenClimateFix/org/predict-pv-yield/e/PRED-541/all?path=validation%2Fresults&attribute=epoch_1

output: 
- print metrics results
- metrics on data - e.g how many data points
- might want to plot time dependent metrics, or deisgn one pager that shows all the results.
- optional, show distribution of input data

## Context
background (https://docs.google.com/document/d/1WgUUKIBW0qI8Qe85a5mPfEqfIzM8nJnCGbqqQY7WlsM/edit#heading=h.jbensnx8gich)

**Comment by peterdudfield** [comment]
plot data distirbutions

![Screenshot 2021-11-30 at 08 35 29](https://user-images.githubusercontent.com/34686298/144012906-00fb73ec-bd3c-4c65-93ec-3e7fee113435.png)

**Comment by peterdudfield** [comment]
![Screenshot 2021-11-30 at 11 21 34](https://user-images.githubusercontent.com/34686298/144038502-65a5bb06-6428-4f4a-839d-4ad029556f4a.png)

**Comment by JackKelly** [comment]
Looks like great progress!  Very nice!

Some thoughts:

* On the "GSP ID" and "GSP ID (Normalized)" plots, will the text "GSP ID" be replaced with a specific GSP ID?
* On the "Forecast Horizon [(Normalized)]" plots:
    * I'd suggest renaming the "Forecast Horizon [(Normalized)]" plots something like "Forecast error as a function of forecast horizon"
    * At the moment, the lines all look pretty much straight.  Maybe just plot a single line?  (e.g. nMAE?)  Or use a different y-axis for RMSE?
* I like the MAE histograms!
    * I'd suggest renaming "GSP ID MAE Histogram [(Normalized)]" to something like "Histogram of MAE for GSP <GSP ID>"
* I'd suggest using _British_ English spellings in our plots because our report to ESO will use British English :slightly_smiling_face: 
* Please label the axes on the "GSP ID [(Normalized)]" timeseries plots
* How are the absolute metrics computed?  Do you first convert the _yield_ forecast (in the range [0, 1]) to MW for each GSP.  And then sum up those MW forecasts across all GSPs?  And compare that sum of MW forecasts to the sum of actual GSP MW output?

**Comment by peterdudfield** [comment]
Thanks @JackKelly 
- The GSP plot is for all the GSP - meant to highlight if any are doing particular badly
- They are pretty straight lines i.e time independent. This tells it own story. But perhaps I could remove ME so that y scales better
- Thanks for all the renamming help
- Good point, ill do British English
- Normalization is done by first divided by capacity and then performing the same calculations. So means each data point is reated equally where as if we dont normalize, the larger GSP sites will dominate. I think both statistic are useful.

**Comment by peterdudfield** [comment]
This is ESO's one
![Screenshot 2021-11-30 at 14 38 37](https://user-images.githubusercontent.com/34686298/144067520-f911a10c-75ce-43a5-a867-1f56930ede2f.png)

**Comment by flowirtz** [comment]
Yeah, sorry, I don't understand too much I'm afraid. My only useful/feedback is: What is `trace0` and `trace1` in the first red/blue plot? Can we rename those to something more meaningful?

Looks great though! :D

**Comment by JackKelly** [comment]
> The GSP plot is for all the GSP - meant to highlight if any are doing particular badly

Ah, got it!  In which case, it might be worth making that really explicit in the subplot title.. something like "Timeseries plot of forecasts for all GSPs"

Looking really great though - thanks so much for doing this!  

BTW, is that plot done using real data or fake data?

**Comment by peterdudfield** [comment]
> > The GSP plot is for all the GSP - meant to highlight if any are doing particular badly
> 
> Ah, got it! In which case, it might be worth making that really explicit in the subplot title.. something like "Timeseries plot of forecasts for all GSPs"
> 
> Looking really great though - thanks so much for doing this!
> 
> BTW, is that plot done using real data or fake data?

I went for 'Forecast Error as a function of GSP ID"

It is using real data, here;s the latest one

![Screenshot 2021-11-30 at 14 49 07](https://user-images.githubusercontent.com/34686298/144069416-fddb583a-3ec7-4647-9d03-4133f8d43f2b.png)

**Comment by JackKelly** [comment]
That's looking super-good!  Awesome work!

I like "forecast error as a function of GSP ID!"

A few more quick thoughts:

* I'd recommend plotting the "forecast normalised error as a func of GSP ID" as a _bar_ chart rather than a line chart.  (because a line chart assumes that it makes sense to interpolate between points, e.g. for a timeseries).
* For the "Histogram of NMAE for GSP", is that histogram computed from errors across all GSPs and across all timesteps?  (i.e. you throw all the errors, for every GSP and every timestep, into a "bucket", and compute the histogram from that "bucket"?)

**Comment by peterdudfield** [comment]
> That's looking super-good! Awesome work!
> 
> I like "forecast error as a function of GSP ID!"
> 
> A few more quick thoughts:
> 
> * I'd recommend plotting the "forecast normalised error as a func of GSP ID" as a _bar_ chart rather than a line chart.  (because a line chart assumes that it makes sense to interpolate between points, e.g. for a timeseries).
> * For the "Histogram of NMAE for GSP", is that histogram computed from errors across all GSPs and across all timesteps?  (i.e. you throw all the errors, for every GSP and every timestep, into a "bucket", and compute the histogram from that "bucket"?)

Thanks @JackKelly ,
- Yea I can do a bar chat. This might struggler to show the two metrics. So I may try a stepped line first. If not I can remove one metric
- The histogram is for each GSP a NMAE is calculated. These 338 results are then summarised in a histogram. So maybe the title could be "Histogram of NMAE for each GSP"
